### ISSUE TITLE
strange User Management behaviour in Dev and Test environments

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#565]
## Describe the bug
In **Dev or Test** environments, when a Catalogue admin user adjusts permissions for another user, upon saving, the checkboxes all uncheck and Catalogue admin user loses their Catalogue admin role.

## To reproduce
Steps to reproduce the behaviour:
1. in Dev or Test, as an IDIR account with the **Catalogue admin user** role already, access the "People" tab
2. Search for a user whose roles you want to adjust
3. Click "Edit" for the user
4. Access the "Roles" tab
5. check the  **Catalogue admin user** role
6. click Save

## Expected behaviour
Upon Save there should be a confirmation:

Status message
The roles have been updated.

and the checkboxes applied prior to Save should persist. The user that made the Save should not lose their roles.

## Additional context
One other strange thing I noticed in Dev or Test was that even though David's First Name and Last Name had been added some time ago, his account is still showing up as:

**Fong, David FIN:EX**

whereas in Prod it displays as expected:
![image](https://github.com/user-attachments/assets/39621dce-37df-46de-b2d1-b89bab51bea5)

**Comment by NicoledeGreef** [comment]
In preliminary discussion when this was discovered, @danhgov noted that the Roles are visible in the **Edit profile** tab for Drupal admin user among many other things, whereas "Catalogue admin" users only see **First name**, **Last name** and **Organization** on the "Edit profile" tab. The "Roles" tab seems to have been set up specifically for "Catalogue admin" users so that they don't see all the extra stuff and perhaps there is an issue with that view?

**Comment by NicoledeGreef** [comment]
If I use an Incognito browser and log in, it appears I still have the **Data catalogue administrator** role. 
I cleared my browser cache in my regular browser window and re-logged in and then I was able to see that I still had the **Data catalogue administrator** role.

I tried adjusting another user's permissions; they were a **Catalogue user**, I tried to make them an **Catalogue editor**. When I click "Save" unfortunately the checkboxes all uncheck. If I move around and come back to that screen the user still has no roles applied.

25-OCT-2024: tried this again today and it's still an issue for me. I tried adjusting roles for a couple of non-active users and all checkboxes were cleared; e.g.:
https://test.cat.data.fin.gov.bc.ca/user/23/edit?destination=/admin/people
https://test.cat.data.fin.gov.bc.ca/user/32/edit?destination=/admin/people

**Comment by david-fong-bc** [comment]
<s>I'm seeing another issue in my experimentation with the JSON API module which might be related. I can successfully make authenticated requests with the PTB API user in the DEV environment, but in the TEST environment, I get 401 Unauthorized, with a detail message saying "No authentication credentials provided", even though when I inspect the request headers being sent, I can see that my `Authorization` header is there. The same `Authorization` header was successfully authenticating my API requests at the end of last week. I asked Mike S. if he had any experience with such an issue before but he didn't, and suggested reaching out to devs / app ops.</s>

I stopped being able to reproduce that issue at the end of the same day, and I unfortunately wasn't able to understand why it happened or how it stopped happening, but if it happens again, I'll try again to understand it.

**Comment by danhgov** [comment]
@david-fong-bc just found us a couple of great leads for fixing this:

- https://github.com/search?q=repo%3Abcgov%2Fbcbb+%22%2Froles%22&type=commits
- https://www.drupal.org/files/issues/2023-11-08/role_delegation-roles-being-stripped-3284859-4.patch

**Comment by chrislaick** [comment]
I was able to reproduce the issue with one additional observation. Just saving the Roles tab form clears out all permissions on the user. You don't have to check/uncheck roles. Currently investigating.

**Comment by chrislaick** [comment]
PR: https://github.com/bcgov/MFIN-Data-Catalogue/pull/569

This issue has been fixed and is currently working in DEV and TEST. Moving to Ready for QA.

**Comment by NicoledeGreef** [comment]
@chrislaick  - I am not experiencing this fix in Dev and Test. I am logged in as my IDIR account which is a Catalogue admin. I tried Incognito with Cache disabled and the issue persists. Whenever I click save on the Roles screen it blanks the checkboxes and indicates a Save has occurred. Any suggestions to get past this?

![Image](https://github.com/user-attachments/assets/a37c4dc7-cbe2-41a4-9f4a-43e9c46c2c66)

**Comment by chrislaick** [comment]
Mysteriously, this has stopped working, so I'm putting it back into In Development and will work on this again.

**Comment by chrislaick** [comment]
This has been fixed in DEV and TEST.

**Comment by david-fong-bc** [comment]
@NicoledeGreef I tested in DEV and TEST, and I can successfully save the user roles for your test user.

**Comment by NicoledeGreef** [comment]
Mysteriously, this is occurring for me in Production. I just tried to adjust Roles on an account in Prod Finance Data Catalogue and had the same symptom:

![Image](https://github.com/user-attachments/assets/188a5586-ae34-4ed6-af1d-f58641955099)

As well, on Jan 17 I tried to adjust roles for a user in Dev and the same issue accourred. I'm going to assume it is also an issue in Test at this rate.

**Comment by chrislaick** [comment]
@NicoledeGreef @david-fong-bc This is fixed in DEV and TEST and ready for QA.

**Comment by NicoledeGreef** [comment]
Thanks @chrislaick  - I have verified it works for me now in Dev and Test.

**Comment by chrislaick** [comment]
@NicoledeGreef Deployed to PROD and working for me.

**Comment by david-fong-bc** [comment]
I just tested with the PTB API user in PROD. I removed its "Data catalogue user" role and then added it back again. Both operations worked! Thanks, Chris :)

**Comment by NicoledeGreef** [comment]
Unfortunately I must report that this issue is manifesting once again in Prod and Test and Dev. Any attempt to Save on the Roles screen clears out the roles for the user.

**Comment by chrislaick** [comment]
Hi @NicoledeGreef I'm looking into this now.

**Comment by chrislaick** [comment]
@NicoledeGreef This issue is now resolved in Dev, Test, Prod. However, I would like to have an internal chat about it in our next meeting.

**Comment by david-fong-bc** [comment]
I'm running into this in PROD right now 😅

**Comment by chrislaick** [comment]
Moving this back to In Development, and assigning @danhgov

**Comment by danhgov** [comment]
Well, I spent a bunch of time to come up with a way to allow us to debug code live on our servers. This seems necessary, because the issue has been occuring on the server, but not reproducible locally. 

The code to make this happen is in this PR: https://github.com/bcgov/MFIN-Data-Catalogue/pull/610
DO NOT MERGE IT! It is just there for reference.

I deployed this test code to the Test server, and -- wouldn't you know it? -- the problem is no longer manifesting there now, even though it was earlier today!!

**Comment by danhgov** [comment]
One thing I did on Test, besides deploying this little hack, was to:
* uninstall the role_delegation module (with `drush un role_deletation`), then
* run `drush cim -y` to re-enable it and re-install all the config that goes with it.

It would be nice to try this on Prod. Or maybe, to copy the Prod DB down to Test again, see if the problem recurs, and run this idea on Test.

**Comment by danhgov** [comment]
Chris also suggested that we simply remove the Roles tab, since this problem only ever seems to manifest when you attempt to modify roles from that page.

**Comment by danhgov** [comment]
This is a VERY mysterious bug. I just rolled the Dev server back to be running the exact same code image that is on Prod. And I dumped the Prod DB, and loaded it on Dev. 

Still:
* The problem manifests on Prod
* It does NOT manifest on Dev

**Comment by david-fong-bc** [comment]
Is there anything noteworthy about the network responses that come back between the working and non-working environmnets? I'd try inspecting them myself in the browser devtools, but I don't have a test account other than the API user.

Does the code image mean the exact same drupal module dependencies and exact same module versions?

**Comment by danhgov** [comment]
>Is there anything noteworthy about the network responses that come back between the working and non-working environmnets?

I'm not sure what to check for here. Do you mean that maybe the javascript being served is different? 

> Does the code image mean the exact same drupal module dependencies and exact same module versions?

Yes, the module versions are all baked into the image.

---

@NicoledeGreef, I'd like to try disabling and re-enabling the role_delegation module on the Prod server. This will mean a brief disruption in that website's proper functionality. Can I try this late in the day, like after 5pm -- perhaps tomorrow (Thurs)?

**Comment by david-fong-bc** [comment]
> I'm not sure what to check for here. Do you mean that maybe the javascript being served is different?

I'm thinking of the HTTP response for the HTTP request to change a user's roles. I'm not that confident that there's be anything enlightening there, but it could be worth comparing with working environments. <s>I would try it myself but I don't want to mess up any accounts.</s> The HTTP request might also be worth looking at, to see what role change data it's sending to the server.

I just tried it in PROD, using my own account with the Data Catalogue Administrator role to view https://cat.data.fin.gov.bc.ca/user/91/roles (roles for PTB API user) and click save with no changes to the checkboxes. The request was sent with form data like this (which I'm guessing is as expected. It had `data_catalogue_api_user` and `data_catalogue_user`, so clicking save with no changes, it sent a request for what it already had):

```none
role_change[data_catalogue_api_user]: data_catalogue_api_user
role_change[data_catalogue_user]: data_catalogue_user
form_build_id: form-zYyhoYCp6onuVdThr2KJR80Mr1c1TMeT6OU6Rl_ouxs
form_token: <I don't know what this is so I redacted it>
form_id: role_delegation_role_assign_form
op: Save
```

So at least it looks like it's not the client sending the wrong thing to the server.

Nothing in the HTTP response looks particularly interesting. It has status 200 and gives the page, now with all the six checkboxes unchecked (the unexpected behaviour that this issue ticket is about).

I wonder if this is in any way related to [Roles being stripped from users when saved if user has no access to roles field #3284859](https://www.drupal.org/project/role_delegation/issues/3284859). It sounds related, but I don't know if I'm understanding the issue description there right. @danhgov is this the issue we're having? (and can you help me add `data_catalogue_api_user` and `data_catalogue_user` back to https://cat.data.fin.gov.bc.ca/user/91 please?)

**Comment by danhgov** [comment]
@david-fong-bc, I added those roles to user 91. 

The drupal issue you refer to is one of the ones that Chris and I have both read several times. In fact, I think we have applied patches from that issue to attempt a resolution of this in the past.

**Comment by david-fong-bc** [comment]
Interestingly, just now when I tried unchecking the IMB organization for [my demo user](https://cat.data.fin.gov.bc.ca/user/179) to see if it would mean it can't see any MRs visible only to specific organizations, when I hit save, it also wiped the Data Catalogue User and Editor roles from the demo user. (Dan helped me restore the roles and organization. (thanks!))

**Comment by danhgov** [comment]
I have a feeling our install of the Role Delegation module is corrupt. Here are the permissions being provided by the Role Delegation module on Dev/Test/Prod, as well as in my localhost, at `admin/people/permissions/module/role_delegation`:

![Image](https://github.com/user-attachments/assets/e90fdefa-56bf-49d3-9080-2bc5d46eea14)

Meanwhile, I tried a fresh install of the Role Delegation module for ESS (only in my localhost), and it looks like this:

![Image](https://github.com/user-attachments/assets/898a7d56-8e07-4657-af9a-64c6e470e5b6)

As you can see, the intended functionality is that there is one permission you can grant for each role on the system. In the case of FDC, this is not the case.

**Comment by danhgov** [comment]
@NicoledeGreef, I'm having another look at this issue, and wanting to be able to see the problem... Are you aware of this currently being an issue on any of Dev, Test or Prod? Or has it mysteriously resolved itself again?

**Comment by danhgov** [comment]
Just to summarize my work on this today:
* Liam made the role_delegation module a dependancy of the bc_dc module, I think so that he could write unit tests that involve the permissions that the role_delegation module provides.
* Liam pulled the permissions that the role_delegation module _normally_ provides into the bc_dc module, again, I think for being able to run his unit tests.
* There was a patch that Liam had applied, which was to fix an issue where roles were being stripped.
* This patch was later removed... I'm not sure why.
* Another patch was later added, this one to provide an option for admins to be able to still see the Roles tab that the role_delegation module provides.
* It is helpful to show the bcbb's main branch alongside the DC's main drupal branch, as the commits on each branch affect each other.
* My note above about the permissions being incorrect is simply because Liam had moved the permissions into bc_dc. You need to look elsewhere in the permissions list to find the role_delegation perms.
* I have a feeling that a good solution would be to completely rip out the Role Delegation module and the tests that Liam had written. Remove any config that this module installs. Then do a fresh install of it.
* Another option would be to disable the OpenID Connect module, to see if that might resolve the problem. We obviously still need that module, but I have a suspicion that that module might be connected to the role-stripping problem. A temporary disabling of it would be an easy way to determine this.

**Comment by david-fong-bc** [comment]
@danhgov The issue doesn't happen for me in TEST right now, but it still happens in PROD (I currently don't have Data Catalogue Admin in DEV so I don't think I can test this myself there). On that note, can you help me add the Data Catalogue User and Data Catalogue Editor roles back to https://cat.data.fin.gov.bc.ca/user/179 please? 😅

**Comment by danhgov** [comment]
@david-fong-bc, I fixed the roles on your prod 179 user.

Also, thanks for the intel on where the issue is currently manifesting. I think I'll clone prod down to Test, to see if I can replicate the issue there where I can fiddle around and try to resolve it.

**Comment by danhgov** [comment]
I just cloned Prod down to Test. I even rolled back the code on Test to exactly match what is on Prod. Somehow, the disappearing roles still happens on Prod, and still does NOT happen on Test. Very puzzling!

It also doesn't happen on Dev or on my localhost. This makes it very hard to debug. :-/

**Comment by danhgov** [comment]
We had previously talked about how OpenPlus had done something to put the roles into their own tab, and that this was the source of the problem. But it turns out that it's the Role Delegation module itself that puts that tab there -- that's just how it works. If you don't have the all-powerful "Administer Users" permission, then you don't see the section on the `user/<userid>/edit` form where the permissions are. The Role Delegation module solves this by adding its own tab.

The maintainers of that module decided that users who DO have "Administer Users" permission don't NEED to see the new Roles tab, and so removed it for them. We later installed a patch from https://www.drupal.org/node/3475414 that allows admin users (with Administer Users) to still redundantly see that tab.

**Comment by danhgov** [comment]
We decided we'd just remove the role_delegation module entirely, and ask Nicole to be careful with the extra powers that come with the 'Administer Users' module.

**Comment by danhgov** [comment]
@chrislaick, FWIW, here is the summary of the role-delegation commit history that I put together earlier today. Note that there are commits from the two complementary repositories:
* BCBB
* MFIN
```
dec  5, 2024 MFIN af0045eb Chris
                                  Add new role_delegation config for roles tab settings
                                  
dec  5, 2024 MFIN 6aa6825e Chris
                                  Update to latest bcbb

dec  5, 2024 BCBB b3f31a79 Chris
                                  Add patch for role_delegation module

                                    3475414 - Allow users with administer users to see Roles tab via a setting
                                    https://www.drupal.org/files/issues/2024-12-05/3475414-role_delegation-5.patch
                                            
dec  5, 2024 BCBB 9454a4c7 Chris
                                  Remove role_delegation patch
                                    - 3284859 - Roles being stripped from users when saved if user has no access to roles field
                                    - https://git.drupalcode.org/project/role_delegation/-/merge_requests/6.diff


nov 24, 2024 MFIN 2f474646 Chris
                                  Update composer and bcbb 
                                  (the corresponding lock file update)

nov 24, 2024 BCBB 6d7dc45d Chris

                                  Update role_delegation patch
                                  Replace                                     
                                    3284859 - Roles being stripped from users when saved if user has no access to roles field
                                    https://www.drupal.org/files/issues/2023-11-08/role_delegation-roles-being-stripped-3284859-4.patch
                                  With 
                                    3284859 - Roles being stripped from users when saved if user has no access to roles field: https://git.drupalcode.org/project/role_delegation/-/merge_requests/6.diff

dec 19, 2023 MFIN 9eeba7be Liam   
                                  Issue #286: Update bcbb to patch role_delegation to prevent roles from being removed
                                  role_delegation-roles-being-stripped-3284859-4.patch (composer.lock)

dec 19, 2023 BCBB c5beb358 Liam   
                                  Patch role_delegation to prevent roles from being removed when editing users
                                  MFIN-Data-Catalogue issue 286
                                  role_delegation-roles-being-stripped-3284859-4.patch (composer.json)

Sep 15, 2023 MFIN a49c98ba Liam   
                                  Issue #162: Install and configure role_delegation module
                                  -- installed normally. 
                                  Also made it a dependency of bc_dc, and 
                                  declared new perms for it in bc_dc.

Sep 11, 2023 BCBB 3529ae64 Craig  
                                  Update composer.json
                                  Add role_delegation module to control what roles business admins can assign. 
                                  Prevents people from being able to give themselves full admin access
```

**Comment by chrislaick** [comment]
@david-fong-bc This has been deployed to DEV and TEST. As a Data Catalogue administrator, could you please try editing a user's account and assigning a role? It should be under the **user/ID/edit** page.

**Comment by david-fong-bc** [comment]
@chrislaick Thanks! I used my main account with the Data Catalogue Admin role to edit the PTB API user (https://test.cat.data.fin.gov.bc.ca/user/91/edit and https://dev.cat.data.fin.gov.bc.ca/user/91/edit). I did a bunch of different combinations of user/editor/api roles in the two environments and things went smoothly. Interestingly, using the Roles tab to edit roles also seemed to work fine in both environments.

**Comment by chrislaick** [comment]
@david-fong-bc Can we close this ticket? :)

**Comment by david-fong-bc** [comment]
@chrislaick Thanks for checking up on this. I don't think this has been deployed to PROD yet. I don't see the change in PROD right now. From the status change above I think Nicole gave the thumbs up to move this to PROD. Then Nicole and I can do a quick test that it's working on PROD and at that point I think we can close this.

**Comment by chrislaick** [comment]
Deployed to PROD.

**Comment by david-fong-bc** [comment]
Thanks, @chrislaick! I just tested in PROD with [my demo account](https://cat.data.fin.gov.bc.ca/user/179/edit) and it's working :)

**Comment by danhgov** [comment]
For the record, when I was trying to figure this ticket out, I worked out a method to be able to edit Drupal code live on the server. How to do that is written up now in our Confluence pages: https://fincsp.atlassian.net/wiki/spaces/FID/pages/330825978/Debugging+code+live+on+the+server

The code that I had been working on for it (abandoned in the repo) is tagged with "issue565--debug-role-delegation".
